version: '3.3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'jdbcdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'developer'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234567'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234567'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3308'
      # Where our data will be persisted
    volumes:
      - ./db:/var/lib/mysql# Names our volume
volumes:
  my-db: